name: Docker
on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/docker.yml
      - Dockerfile
  push:
    paths:
      - .github/workflows/docker.yml
      - Dockerfile
    branches-ignore:
      - master
  release:
    types:
      - published
permissions:
  contents: read
jobs:
  ubuntu:
    if: startsWith(github.repository, 'Homebrew/')
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        version: ["18.04", "20.04", "22.04"]
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Fetch origin/master from Git
        run: git fetch origin master

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@6e04d228eb30da1757ee4e1dd75a0ec73a653e06 #v3.1.1
        with:
          cosign-release: 'v2.1.1'

      - name: Build Docker image
        run: |
          brew_version="$(git describe --tags --dirty --abbrev=7)"
          echo "Building for Homebrew ${brew_version}"
          docker build -t brew \
               --build-arg=version=${{matrix.version}} \
               --label org.opencontainers.image.created="$(date --rfc-3339=seconds --utc)" \
               --label org.opencontainers.image.url="https://brew.sh" \
               --label org.opencontainers.image.documentation="https://docs.brew.sh" \
               --label org.opencontainers.image.source="https://github.com/${GITHUB_REPOSITORY}" \
               --label org.opencontainers.image.version="${brew_version}" \
               --label org.opencontainers.image.revision="${GITHUB_SHA}" \
               --label org.opencontainers.image.vendor="${GITHUB_REPOSITORY_OWNER}" \
               --label org.opencontainers.image.licenses="BSD-2-Clause" \
               .

      - name: Run brew test-bot --only-setup
        run: docker run --rm brew brew test-bot --only-setup

      - name: Deploy the tagged Docker image to GitHub Packages
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          brew_version="${GITHUB_REF:10}"
          echo "brew_version=${brew_version}" >> "${GITHUB_ENV}"
          echo $${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag brew "ghcr.io/gsoc2/ubuntu${{matrix.version}}:${brew_version}"
          docker push "ghcr.io/gsoc2/ubuntu${{matrix.version}}:${brew_version}"
          docker tag brew "ghcr.io/gsoc2/ubuntu${{matrix.version}}:latest"
          docker push "ghcr.io/gsoc2/ubuntu${{matrix.version}}:latest"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy the homebrew/brew Docker image to GitHub Packages and Docker Hub
        if: startsWith(github.ref, 'refs/tags/') && matrix.version == '22.04'
        run: |
          docker tag brew "ghcr.io/gsoc2/brew:${brew_version}"
          docker push "ghcr.io/gsoc2/brew:${brew_version}"
          docker tag brew "ghcr.io/gsoc2/brew:latest"
          docker push "ghcr.io/gsoc2/brew:latest"
          docker tag brew "gsoc2/brew:${brew_version}"
          docker push "gsoc2/brew:${brew_version}"
          docker tag brew "gsoc2/brew:latest"
          docker push "gsoc2/brew:latest"
